# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import asset_service_pb2 as grpc_dot_asset__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc/asset_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssetServiceStub(object):
    """Work 가 호출하는 RPC 만 추린 정의.
    원본: moaje-grpc-contracts/proto/grpc/asset_service.proto
    Asset 서버는 송금 관련 RPC 도 제공하지만 Work 는 사용하지 않는다.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyCashflow = channel.unary_unary(
                '/moaje.grpc.asset.AssetService/GetDailyCashflow',
                request_serializer=grpc_dot_asset__service__pb2.GetDailyCashflowRequest.SerializeToString,
                response_deserializer=grpc_dot_asset__service__pb2.GetDailyCashflowResponse.FromString,
                _registered_method=True)


class AssetServiceServicer(object):
    """Work 가 호출하는 RPC 만 추린 정의.
    원본: moaje-grpc-contracts/proto/grpc/asset_service.proto
    Asset 서버는 송금 관련 RPC 도 제공하지만 Work 는 사용하지 않는다.
    """

    def GetDailyCashflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyCashflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyCashflow,
                    request_deserializer=grpc_dot_asset__service__pb2.GetDailyCashflowRequest.FromString,
                    response_serializer=grpc_dot_asset__service__pb2.GetDailyCashflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moaje.grpc.asset.AssetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moaje.grpc.asset.AssetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetService(object):
    """Work 가 호출하는 RPC 만 추린 정의.
    원본: moaje-grpc-contracts/proto/grpc/asset_service.proto
    Asset 서버는 송금 관련 RPC 도 제공하지만 Work 는 사용하지 않는다.
    """

    @staticmethod
    def GetDailyCashflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moaje.grpc.asset.AssetService/GetDailyCashflow',
            grpc_dot_asset__service__pb2.GetDailyCashflowRequest.SerializeToString,
            grpc_dot_asset__service__pb2.GetDailyCashflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
