# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/asset_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'grpc/asset_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc.common import resources_pb2 as common_dot_resources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc/asset_service.proto\x12\x10moaje.grpc.asset\x1a\x16\x63ommon/resources.proto\"\xfe\x01\n\x17GetDailyCashflowRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12,\n\x0f\x65xpected_income\x18\x02 \x01(\x0b\x32\x13.moaje.common.Money\x12+\n\x0e\x66ixed_expenses\x18\x03 \x01(\x0b\x32\x13.moaje.common.Money\x12)\n\x0c\x65vent_buffer\x18\x04 \x01(\x0b\x32\x13.moaje.common.Money\x12\x1e\n\x16\x64\x61ys_until_next_payday\x18\x05 \x01(\x05\x12\x15\n\rsnapshot_date\x18\x06 \x01(\t\x12\x15\n\rforce_refresh\x18\x07 \x01(\x08\"\xc0\x02\n\x18GetDailyCashflowResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12,\n\x0f\x63urrent_balance\x18\x02 \x01(\x0b\x32\x13.moaje.common.Money\x12,\n\x0f\x65xpected_income\x18\x03 \x01(\x0b\x32\x13.moaje.common.Money\x12+\n\x0e\x66ixed_expenses\x18\x04 \x01(\x0b\x32\x13.moaje.common.Money\x12)\n\x0c\x65vent_buffer\x18\x05 \x01(\x0b\x32\x13.moaje.common.Money\x12\x1e\n\x16\x64\x61ys_until_next_payday\x18\x06 \x01(\x05\x12(\n\x0b\x64\x61ily_limit\x18\x07 \x01(\x0b\x32\x13.moaje.common.Money\x12\x15\n\rsnapshot_date\x18\x08 \x01(\t2y\n\x0c\x41ssetService\x12i\n\x10GetDailyCashflow\x12).moaje.grpc.asset.GetDailyCashflowRequest\x1a*.moaje.grpc.asset.GetDailyCashflowResponseB\x18\n\x14\x63om.moaje.grpc.assetP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.asset_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.moaje.grpc.assetP\001'
  _globals['_GETDAILYCASHFLOWREQUEST']._serialized_start=71
  _globals['_GETDAILYCASHFLOWREQUEST']._serialized_end=325
  _globals['_GETDAILYCASHFLOWRESPONSE']._serialized_start=328
  _globals['_GETDAILYCASHFLOWRESPONSE']._serialized_end=648
  _globals['_ASSETSERVICE']._serialized_start=650
  _globals['_ASSETSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
