# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/work_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc/work_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grpc/work_service.proto\x12\x0fmoaje.grpc.work\"\xb8\x01\n\x15GetDailyBudgetRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63urrent_balance\x18\x03 \x01(\t\x12\x17\n\x0f\x65xpected_income\x18\x04 \x01(\t\x12\x16\n\x0e\x66ixed_expenses\x18\x05 \x01(\t\x12\x19\n\x11\x64\x61ys_until_payday\x18\x06 \x01(\x05\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"y\n\x16GetDailyBudgetResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x61ily_limit\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x64vice\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"S\n\x15\x43heckBlacklistRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"g\n\x16\x43heckBlacklistResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x12\n\nis_blocked\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\xd3\x01\n\x0bWorkService\x12\x61\n\x0eGetDailyBudget\x12&.moaje.grpc.work.GetDailyBudgetRequest\x1a\'.moaje.grpc.work.GetDailyBudgetResponse\x12\x61\n\x0e\x43heckBlacklist\x12&.moaje.grpc.work.CheckBlacklistRequest\x1a\'.moaje.grpc.work.CheckBlacklistResponseB\x17\n\x13\x63om.moaje.grpc.workP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.work_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.moaje.grpc.workP\001'
  _globals['_GETDAILYBUDGETREQUEST']._serialized_start=45
  _globals['_GETDAILYBUDGETREQUEST']._serialized_end=229
  _globals['_GETDAILYBUDGETRESPONSE']._serialized_start=231
  _globals['_GETDAILYBUDGETRESPONSE']._serialized_end=352
  _globals['_CHECKBLACKLISTREQUEST']._serialized_start=354
  _globals['_CHECKBLACKLISTREQUEST']._serialized_end=437
  _globals['_CHECKBLACKLISTRESPONSE']._serialized_start=439
  _globals['_CHECKBLACKLISTRESPONSE']._serialized_end=542
  _globals['_WORKSERVICE']._serialized_start=545
  _globals['_WORKSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
