# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import work_service_pb2 as grpc_dot_work__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc/work_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyBudget = channel.unary_unary(
                '/moaje.grpc.work.WorkService/GetDailyBudget',
                request_serializer=grpc_dot_work__service__pb2.GetDailyBudgetRequest.SerializeToString,
                response_deserializer=grpc_dot_work__service__pb2.GetDailyBudgetResponse.FromString,
                _registered_method=True)
        self.CheckBlacklist = channel.unary_unary(
                '/moaje.grpc.work.WorkService/CheckBlacklist',
                request_serializer=grpc_dot_work__service__pb2.CheckBlacklistRequest.SerializeToString,
                response_deserializer=grpc_dot_work__service__pb2.CheckBlacklistResponse.FromString,
                _registered_method=True)


class WorkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDailyBudget(self, request, context):
        """일일 가용 생활비 조회 (Asset -> Work)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBlacklist(self, request, context):
        """FDS 블랙리스트 여부 확인 (Gateway -> Work)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyBudget,
                    request_deserializer=grpc_dot_work__service__pb2.GetDailyBudgetRequest.FromString,
                    response_serializer=grpc_dot_work__service__pb2.GetDailyBudgetResponse.SerializeToString,
            ),
            'CheckBlacklist': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBlacklist,
                    request_deserializer=grpc_dot_work__service__pb2.CheckBlacklistRequest.FromString,
                    response_serializer=grpc_dot_work__service__pb2.CheckBlacklistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moaje.grpc.work.WorkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moaje.grpc.work.WorkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDailyBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moaje.grpc.work.WorkService/GetDailyBudget',
            grpc_dot_work__service__pb2.GetDailyBudgetRequest.SerializeToString,
            grpc_dot_work__service__pb2.GetDailyBudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBlacklist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moaje.grpc.work.WorkService/CheckBlacklist',
            grpc_dot_work__service__pb2.CheckBlacklistRequest.SerializeToString,
            grpc_dot_work__service__pb2.CheckBlacklistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
