# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/asset_events.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'events/asset_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import resources_pb2 as common_dot_resources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65vents/asset_events.proto\x12\x12moaje.events.asset\x1a\x16\x63ommon/resources.proto\"\xbc\x02\n\x1b\x41ssetTransferRequestedEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0btransfer_id\x18\x02 \x01(\x03\x12\x1c\n\x14\x61sset_transaction_id\x18\x03 \x01(\x03\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\x12\n\n\x02\x63i\x18\x05 \x01(\t\x12\x11\n\tuser_name\x18\x06 \x01(\t\x12\x14\n\x0cphone_number\x18\x07 \x01(\t\x12\x1d\n\x15withdrawal_account_id\x18\x08 \x01(\t\x12\x19\n\x11\x64\x65posit_bank_code\x18\t \x01(\t\x12\x1e\n\x16\x64\x65posit_account_number\x18\n \x01(\t\x12#\n\x06\x61mount\x18\x0b \x01(\x0b\x32\x13.moaje.common.Money\x12\x13\n\x0boccurred_at\x18\x0c \x01(\t\"\x94\x01\n\x19\x44\x61ilyCashflowUpdatedEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12(\n\x0b\x64\x61ily_limit\x18\x03 \x01(\x0b\x32\x13.moaje.common.Money\x12\x15\n\rsnapshot_date\x18\x04 \x01(\t\x12\x13\n\x0boccurred_at\x18\x05 \x01(\t\"\xf9\x02\n\x19TransactionSucceededEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x03\x12\x1d\n\x15public_transaction_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\x12\x12\n\naccount_id\x18\x05 \x01(\x03\x12\x15\n\raccount_token\x18\x06 \x01(\t\x12\x1f\n\x17\x65xternal_transaction_id\x18\x07 \x01(\t\x12\x18\n\x10transaction_type\x18\x08 \x01(\t\x12#\n\x06\x61mount\x18\t \x01(\x0b\x32\x13.moaje.common.Money\x12\x14\n\x0ctarget_token\x18\n \x01(\t\x12\x36\n\x19\x62\x61lance_after_transaction\x18\x0b \x01(\x0b\x32\x13.moaje.common.Money\x12\x14\n\x0csucceeded_at\x18\x0c \x01(\t\x12\x13\n\x0boccurred_at\x18\r \x01(\tB\x1a\n\x16\x63om.moaje.events.assetP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.asset_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.moaje.events.assetP\001'
  _globals['_ASSETTRANSFERREQUESTEDEVENT']._serialized_start=74
  _globals['_ASSETTRANSFERREQUESTEDEVENT']._serialized_end=390
  _globals['_DAILYCASHFLOWUPDATEDEVENT']._serialized_start=393
  _globals['_DAILYCASHFLOWUPDATEDEVENT']._serialized_end=541
  _globals['_TRANSACTIONSUCCEEDEDEVENT']._serialized_start=544
  _globals['_TRANSACTIONSUCCEEDEDEVENT']._serialized_end=921
# @@protoc_insertion_point(module_scope)
