syntax = "proto3";
package moaje.grpc.asset;

import "common/resources.proto";

option java_package = "com.moaje.grpc.asset";
option java_multiple_files = true;

service AssetService {
  rpc GetDailyCashflow(GetDailyCashflowRequest) returns (GetDailyCashflowResponse);
}

message GetDailyCashflowRequest {
  string user_id = 1;
  moaje.common.Money expected_income = 2;
  moaje.common.Money fixed_expenses = 3;
  moaje.common.Money event_buffer = 4;
  int32 days_until_next_payday = 5;
  string snapshot_date = 6;
  bool force_refresh = 7;
}

message GetDailyCashflowResponse {
  string user_id = 1;
  moaje.common.Money current_balance = 2;
  moaje.common.Money expected_income = 3;
  moaje.common.Money fixed_expenses = 4;
  moaje.common.Money event_buffer = 5;
  int32 days_until_next_payday = 6;
  moaje.common.Money daily_limit = 7;
  string snapshot_date = 8;
}
